feat(@fireblocks/recovery-utility): :sparkles: add Jetton support
fireblocks/recovery pull request #105
Opened 2024-12-16 09:22 UTC by TomerHFB

Add the ability to derive Jetton wallets a withdraw the assets

2024-12-16 09:43 UTC, a0ngo requested changes

2024-12-16 09:43 UTC, a0ngo commented on apps/recovery-relay/components/WithdrawModal/CreateTransaction/index.tsx
> +  const derivation = wallet?.derivations?.get(`${asset?.id}-${fromAddress}`); // fix for token support
Remove comment

2024-12-16 09:43 UTC, a0ngo commented on apps/recovery-relay/components/WithdrawModal/index.tsx
> +                        `${inboundRelayParams?.signedTx.assetId}-${inboundRelayParams?.signedTx.from}`,
Move this to a separate function in the shared-package and all instances where we do X-Y format should call that function with the parameters instead. This way if we need to alter this in the future we can without having to go through each location it is used.

2024-12-16 09:43 UTC, a0ngo commented on apps/recovery-relay/components/WithdrawModal/index.tsx
> +                        `${inboundRelayParams?.signedTx.assetId}-${inboundRelayParams?.signedTx.from}`,
And remove comment

2024-12-16 09:43 UTC, a0ngo commented on apps/recovery-relay/context/Workspace.tsx
> +        if (input.assetId in WalletClasses) {
Please add log saying that we identified this derivation as a token

2024-12-16 09:43 UTC, a0ngo commented on apps/recovery-relay/lib/wallets/Jetton/index.ts
> +  }
Do not leave this as throwing an error, please change it to some label. See ADA for an example

2024-12-16 09:43 UTC, a0ngo commented on apps/recovery-relay/lib/wallets/Jetton/index.ts
The generate structure we want to follow for files is:
--- imports ---
--- class definition ---
--- members (memo, tokenaddress, etc...) ---
--- constructor ---
--- public functions ---
--- private functions ---


Please re-organize this to match it

2024-12-16 09:43 UTC, a0ngo commented on apps/recovery-relay/lib/wallets/index.ts
This should be with a "fillJetton" type function as we discussed about EVM

2024-12-16 09:43 UTC, a0ngo commented on apps/recovery-relay/lib/wallets/types.ts
> +  insufficientFeeBalance?: boolean;
Unclear, please update to the below and update references

```suggestion
  insufficientBalanceForTokenTransfer?: boolean;
```

2024-12-16 09:43 UTC, a0ngo commented on apps/recovery-utility/renderer/components/Modals/WithdrawModal/SignTransaction/index.tsx
> +      ?.derivations.get(`${inboundRelayParams?.unsignedTx.assetId}-${inboundRelayParams?.unsignedTx.from}`);
See previous comment about X-Y

2024-12-16 09:43 UTC, a0ngo commented on apps/recovery-utility/renderer/context/Workspace.tsx
> +      if (config?.address && isTransferableToken(input.assetId)) {
`config?.address` is already done as part of isTransferableToken, remove it please

2024-12-16 09:43 UTC, a0ngo commented on apps/recovery-utility/renderer/context/Workspace.tsx
> +        transferableToken = true;
Add log

2024-12-16 09:43 UTC, a0ngo commented on apps/recovery-utility/renderer/lib/wallets/Jetton/index.ts
> +    const JettonTransferOpcode = 0x0f8a7ea5;
```suggestion
    const jettonTransferOpcode = 0x0f8a7ea5;
```

2024-12-16 09:43 UTC, a0ngo commented on apps/recovery-utility/renderer/lib/wallets/Jetton/index.ts
See previous comment about file structure

2024-12-16 09:43 UTC, a0ngo commented on apps/recovery-utility/renderer/lib/wallets/index.ts
> +
Please implement fillJettons

2024-12-16 09:43 UTC, a0ngo commented on apps/recovery-utility/renderer/lib/wallets/index.ts
> +  DOGS_TON: Jetton,
replace with fillJettons

2024-12-16 09:43 UTC, a0ngo commented on packages/shared/hooks/useBaseWorkspace/reduceDerivations.ts
> +    wallet.derivations.set(`${derivation.assetId}-${derivation.address}`, derivation); // fix for token support
Previous comment about X-Y

2024-12-16 09:43 UTC, a0ngo commented on packages/shared/lib/validateAddress.ts
> +      case 'NOTCOIN_TON':
See if we can generalize to just "Jetton" or work by protocol instead of asset ID, if we use assetId this switch-case will be massive

2024-12-16 09:43 UTC, a0ngo commented on packages/wallet-derivation/wallets/chains/index.ts
> +      return Jetton;
Please replace with a fillJetton like function

2024-12-16 14:11 UTC, TomerHFB commented
Fixes applied @a0ngo

2024-12-17 11:14 UTC, TomerHFB commented on apps/recovery-utility/renderer/lib/wallets/Jetton/index.ts
I don't see any discrepancy in the file order, please clarify?

2024-12-18 12:06 UTC, a0ngo approved these changes
lgtm

2024-12-18 12:06 UTC, merged